import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import logging
from config import config

logger = logging.getLogger(__name__)


async def send_email(to: str, subject: str, body_markdown: str) -> dict:
    """
    Send the final research report as an email.

    Why plain smtplib and not SendGrid/Mailgun?
    For a portfolio project, SMTP via Gmail is zero cost and zero signup.
    It shows you understand the actual email protocol, not just a black-box API.

    For production you'd use SendGrid because it gives you:
    - Delivery tracking (did the email arrive?)
    - Bounce handling
    - Better deliverability (your IP isn't flagged as spam)

    Gmail App Password setup (required):
    1. Enable 2FA on your Google account
    2. Go to myaccount.google.com/apppasswords
    3. Generate a password for "Mail"
    4. Use THAT in SMTP_PASSWORD, not your real Gmail password

    Why send both plain text AND HTML?
    Called multipart/alternative. Email clients pick the best version
    they can render. Terminal email clients get clean text.
    Gmail/Outlook render the HTML. This is standard professional practice.
    """
    if not config.SMTP_USER or not config.SMTP_PASSWORD:
        logger.warning("SMTP not configured - skipping email")
        return {"success": False, "error": "SMTP credentials not set in .env"}

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = config.SMTP_USER
        msg["To"] = to

        # Plain text version - readable as-is
        plain_part = MIMEText(body_markdown, "plain", "utf-8")

        # Simple HTML version - wrap in basic styling
        html_body = body_markdown.replace("\n", "<br>")
        html_full = f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 800px;
                     margin: 0 auto; padding: 20px; line-height: 1.6;">
            {html_body}
            <hr style="margin-top: 40px; border: none; border-top: 1px solid #eee;">
            <p style="font-size: 12px; color: #999;">
                Generated by Research Agent · Powered by Groq + LangGraph
            </p>
        </body>
        </html>
        """
        html_part = MIMEText(html_full, "html", "utf-8")

        # Plain first, HTML second.
        # Email clients prefer the LAST part they can render.
        # So plain → HTML means HTML is shown by default.
        msg.attach(plain_part)
        msg.attach(html_part)

        with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()        # upgrade to encrypted connection
            server.login(config.SMTP_USER, config.SMTP_PASSWORD)
            server.sendmail(config.SMTP_USER, to, msg.as_string())

        logger.info(f"Email sent to {to}")
        return {"success": True, "error": ""}

    except smtplib.SMTPAuthenticationError:
        error = "Gmail auth failed. Did you use an App Password?"
        logger.error(error)
        return {"success": False, "error": error}

    except Exception as e:
        logger.error(f"Email failed: {e}")
        return {"success": False, "error": str(e)}